name: Upload / download artifacts

# on: [push, pull_request]
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
# setting up python env
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

# installing libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

# running the test file and putting it in a file test-results
      - name: Run tests
        run: |
          mkdir -p test-results
          pytest --junitxml=test-results/results.xml

# uploading test-result file in artifacts
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/

# running the main.py file and saving the result in the file main-results as txt
      - name: Run main.py file
        run: |
          mkdir -p main-results
          python src/main.py
          python src/main.py > main-results/main_result.txt

# uploading the main.py results on artifacts
      - name: Upload main.py results
        uses: actions/upload-artifact@v3
        with:
          name: main-results
          path: main-results/

# building the project
      - name: Build project
        run: |
          mkdir -p build
          echo "This is a build output" > build/output.txt

# uploading build project on artifact
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/

# downloading the artifacts on the runner
  download:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download test results artifact
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: downloaded-test-results/

      - name: Download main results artifact
        uses: actions/download-artifact@v3
        with:
          name: main-results
          path: downloaded-main-results/

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: downloaded-build-artifacts/

# viewing the downloaded artifacts
      - name: Display downloaded test results
        run: cat downloaded-test-results/results.xml
        
      - name: Display downloaded main results
        run: cat downloaded-main-results/main_result.txt

      - name: Display downloaded build artifacts
        run: cat downloaded-build-artifacts/output.txt


