name: Timestamp Example

on: [workflow_dispatch]

jobs:
  set-timestamp:
    runs-on: ubuntu-latest
    outputs:
      steps: ${{ steps.timestamp.outputs }}
    steps:
      - name: Set Timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +"%Y%m%d%H%M%S")" >> $GITHUB_ENV

  use-timestamp:
    needs: set-timestamp
    runs-on: ubuntu-latest
    steps:
      - name: Use Timestamp
        run: echo "Timestamp is $TIMESTAMP"
